deck = "a2::aggettivi_avanzati"
model = "basic"

[[notes]]
note_id = 10001
tags = [
    "a2",
    "aggettivi_avanzati",
]
fields = [
    "ğŸŒŸ **affascinante**",
    "Meaning: fascinating\nExample: Questo museo Ã¨ davvero **affascinante**",
]

[[notes]]
note_id = 10002
tags = [
    "a2",
    "aggettivi_avanzati",
]
fields = [
    "â³ **paziente**",
    "Meaning: patient\nExample: Devi essere **paziente** con i bambini",
]

[[notes]]
note_id = 10003
tags = [
    "a2",
    "aggettivi_avanzati",
]
fields = [
    "âš¡ï¸ **impaziente**",
    "Meaning: impatient\nExample: Sono **impaziente** di sapere il risultato",
]

[[notes]]
note_id = 10004
tags = [
    "a2",
    "aggettivi_avanzati",
]
fields = [
    "ğŸ¨ **creativo**",
    "Meaning: creative\nExample: Mia sorella Ã¨ molto **creativa**",
]

[[notes]]
note_id = 10005
tags = [
    "a2",
    "aggettivi_avanzati",
]
fields = [
    "ğŸ¤ **onesto**",
    "Meaning: honest\nExample: Ãˆ importante essere **onesti**",
]

[[notes]]
note_id = 10006
tags = [
    "a2",
    "aggettivi_avanzati",
]
fields = [
    "ğŸ¦ **coraggioso**",
    "Meaning: courageous\nExample: Quella ragazza Ã¨ veramente **coraggiosa**",
]

[[notes]]
note_id = 10007
tags = [
    "a2",
    "aggettivi_avanzati",
]
fields = [
    "ğŸ **generoso**",
    "Meaning: generous\nExample: Il mio amico Ã¨ sempre stato **generoso**",
]

[[notes]]
note_id = 10008
tags = [
    "a2",
    "aggettivi_avanzati",
]
fields = [
    "ğŸ™ˆ **timido**",
    "Meaning: shy\nExample: In classe sono un poâ€™ **timido**",
]

[[notes]]
note_id = 10009
tags = [
    "a2",
    "aggettivi_avanzati",
]
fields = [
    "ğŸ‰ **socievole**",
    "Meaning: sociable\nExample: Marco Ã¨ molto **socievole**",
]

[[notes]]
note_id = 10010
tags = [
    "a2",
    "aggettivi_avanzati",
]
fields = [
    "ğŸ”ï¸ **ambizioso**",
    "Meaning: ambitious\nExample: Ha progetti molto **ambiziosi**",
]

[[notes]]
note_id = 10011
tags = [
    "a2",
    "aggettivi_avanzati",
]
fields = [
    "ğŸŒˆ **ottimista**",
    "Meaning: optimistic\nExample: Nonostante tutto rimango **ottimista**",
]

[[notes]]
note_id = 10012
tags = [
    "a2",
    "aggettivi_avanzati",
]
fields = [
    "ğŸŒ§ï¸ **pessimista**",
    "Meaning: pessimistic\nExample: A volte divento un poâ€™ **pessimista**",
]

[[notes]]
note_id = 10013
tags = [
    "a2",
    "aggettivi_avanzati",
]
fields = [
    "ğŸ›€ **rilassato**",
    "Meaning: relaxed\nExample: Dopo la spa mi sento **rilassato**",
]

[[notes]]
note_id = 10014
tags = [
    "a2",
    "aggettivi_avanzati",
]
fields = [
    "ğŸ˜¬ **nervoso**",
    "Meaning: nervous\nExample: Sono **nervoso** per lâ€™esame",
]

[[notes]]
note_id = 10015
tags = [
    "a2",
    "aggettivi_avanzati",
]
fields = [
    "ğŸ’– **affettuoso**",
    "Meaning: affectionate\nExample: Il mio cane Ã¨ molto **affettuoso**",
]

[[notes]]
note_id = 10016
tags = [
    "a2",
    "aggettivi_avanzati",
]
fields = [
    "ğŸ©· **sensibile**",
    "Meaning: sensitive\nExample: Sei troppo **sensibile**",
]

[[notes]]
note_id = 10017
tags = [
    "a2",
    "aggettivi_avanzati",
]
fields = [
    "ğŸ—£ï¸ **sincero**",
    "Meaning: sincere\nExample: Apprezzo quando sei **sincero**",
]

[[notes]]
note_id = 10018
tags = [
    "a2",
    "aggettivi_avanzati",
]
fields = [
    "ğŸ¯ **determinato**",
    "Meaning: determined\nExample: Lei Ã¨ molto **determinata**",
]

[[notes]]
note_id = 10019
tags = [
    "a2",
    "aggettivi_avanzati",
]
fields = [
    "ğŸ” **curioso**",
    "Meaning: curious\nExample: Sono **curioso** di sapere di piÃ¹",
]

[[notes]]
note_id = 10020
tags = [
    "a2",
    "aggettivi_avanzati",
]
fields = [
    "ğŸ¤· **indeciso**",
    "Meaning: indecisive\nExample: Sono ancora **indeciso** sulla scelta",
]
