deck = "basic::saluti"
model = "basic"

[[notes]]
note_id = 10010
tags = [
    "basic",
    "cortesia",
]
fields = [
    "ğŸ™ **Per favore**",
    "Meaning: Please\nExample: Un caffÃ¨, **per favore**.",
]

[[notes]]
note_id = 10011
tags = [
    "basic",
    "cortesia",
]
fields = [
    "ğŸ™ **Grazie**",
    "Meaning: Thank you\nExample: **Grazie** per l'aiuto.",
]

[[notes]]
note_id = 10012
tags = [
    "basic",
    "cortesia",
]
fields = [
    "ğŸ™ **Prego**",
    "Meaning: You're welcome\nExample: \"Grazie!\" \"**Prego**!\"",
]
