deck = "a1::aggettivi"
model = "basic"

[[notes]]
note_id = 10001
tags = [
    "a1",
    "aggettivi",
]
fields = [
    "ğŸ˜Š **bello**",
    "Meaning: beautiful\nExample: Il fiore Ã¨ **bello**",
]

[[notes]]
note_id = 10002
tags = [
    "a1",
    "aggettivi",
]
fields = [
    "ğŸ˜ **brutto**",
    "Meaning: ugly/bad\nExample: Che giorno **brutto**!",
]

[[notes]]
note_id = 10003
tags = [
    "a1",
    "aggettivi",
]
fields = [
    "ğŸ§’ **piccolo**",
    "Meaning: small\nExample: Ho un cane **piccolo**",
]

[[notes]]
note_id = 10004
tags = [
    "a1",
    "aggettivi",
]
fields = [
    "ğŸ¦ **grande**",
    "Meaning: big\nExample: La montagna Ã¨ **grande**",
]

[[notes]]
note_id = 10005
tags = [
    "a1",
    "aggettivi",
]
fields = [
    "ğŸ†• **nuovo**",
    "Meaning: new\nExample: Ho comprato un **libro** nuovo",
]

[[notes]]
note_id = 10006
tags = [
    "a1",
    "aggettivi",
]
fields = [
    "ğŸ“š **vecchio**",
    "Meaning: old\nExample: Questo giornale Ã¨ **vecchio**",
]

[[notes]]
note_id = 10007
tags = [
    "a1",
    "aggettivi",
]
fields = [
    "â†”ï¸ **lungo**",
    "Meaning: long\nExample: Ha un vestito **lungo**",
]

[[notes]]
note_id = 10008
tags = [
    "a1",
    "aggettivi",
]
fields = [
    "â†•ï¸ **corto**",
    "Meaning: short\nExample: Ha capelli **corti**",
]

[[notes]]
note_id = 10009
tags = [
    "a1",
    "aggettivi",
]
fields = [
    "ğŸ” **alto**",
    "Meaning: tall/high\nExample: Il muro Ã¨ **alto**",
]

[[notes]]
note_id = 10010
tags = [
    "a1",
    "aggettivi",
]
fields = [
    "ğŸ“‰ **basso**",
    "Meaning: low/short\nExample: Il tavolo Ã¨ **basso**",
]

[[notes]]
note_id = 10011
tags = [
    "a1",
    "aggettivi",
]
fields = [
    "ğŸ **veloce**",
    "Meaning: fast\nExample: La macchina Ã¨ **veloce**",
]

[[notes]]
note_id = 10012
tags = [
    "a1",
    "aggettivi",
]
fields = [
    "ğŸ¢ **lento**",
    "Meaning: slow\nExample: Il treno Ã¨ **lento**",
]

[[notes]]
note_id = 10013
tags = [
    "a1",
    "aggettivi",
]
fields = [
    "ğŸ˜ƒ **simpatico**",
    "Meaning: nice/friendly\nExample: Il professore Ã¨ **simpatico**",
]

[[notes]]
note_id = 10014
tags = [
    "a1",
    "aggettivi",
]
fields = [
    "ğŸ‹ï¸â€â™‚ï¸ **difficile**",
    "Meaning: difficult\nExample: Questo esercizio Ã¨ **difficile**",
]

[[notes]]
note_id = 10015
tags = [
    "a1",
    "aggettivi",
]
fields = [
    "ğŸ†— **facile**",
    "Meaning: easy\nExample: La domanda Ã¨ **facile**",
]

[[notes]]
note_id = 10016
tags = [
    "a1",
    "aggettivi",
]
fields = [
    "ğŸ˜Œ **calmo**",
    "Meaning: calm\nExample: Il lago Ã¨ **calmo**",
]

[[notes]]
note_id = 10017
tags = [
    "a1",
    "aggettivi",
]
fields = [
    "ğŸ‰ **rumoroso**",
    "Meaning: noisy\nExample: Il mercato Ã¨ **rumoroso**",
]

[[notes]]
note_id = 10018
tags = [
    "a1",
    "aggettivi",
]
fields = [
    "ğŸ’° **caro**",
    "Meaning: expensive\nExample: Questo ristorante Ã¨ **caro**",
]

[[notes]]
note_id = 10019
tags = [
    "a1",
    "aggettivi",
]
fields = [
    "ğŸ’¸ **economico**",
    "Meaning: cheap\nExample: Il biglietto Ã¨ **economico**",
]

[[notes]]
note_id = 10020
tags = [
    "a1",
    "aggettivi",
]
fields = [
    "ğŸ™‚ **felice**",
    "Meaning: happy\nExample: Sono **felice** oggi",
]
