deck = "a1::colori"
model = "basic"

[[notes]]
note_id = 10001
tags = [
    "a1",
    "colori",
]
fields = [
    "ğŸ”´ **rosso**",
    "Meaning: red\nExample: Il semaforo Ã¨ **rosso**",
]

[[notes]]
note_id = 10002
tags = [
    "a1",
    "colori",
]
fields = [
    "ğŸŸ  **arancione**",
    "Meaning: orange\nExample: Lâ€™auto Ã¨ **arancione**",
]

[[notes]]
note_id = 10003
tags = [
    "a1",
    "colori",
]
fields = [
    "ğŸŸ¡ **giallo**",
    "Meaning: yellow\nExample: Il sole Ã¨ **giallo**",
]

[[notes]]
note_id = 10004
tags = [
    "a1",
    "colori",
]
fields = [
    "ğŸŸ¢ **verde**",
    "Meaning: green\nExample: Lâ€™erba Ã¨ **verde**",
]

[[notes]]
note_id = 10005
tags = [
    "a1",
    "colori",
]
fields = [
    "ğŸ”µ **blu**",
    "Meaning: blue\nExample: Il cielo Ã¨ **blu**",
]

[[notes]]
note_id = 10006
tags = [
    "a1",
    "colori",
]
fields = [
    "ğŸŸ£ **viola**",
    "Meaning: purple\nExample: La maglietta Ã¨ **viola**",
]

[[notes]]
note_id = 10007
tags = [
    "a1",
    "colori",
]
fields = [
    "ğŸŸ¤ **marrone**",
    "Meaning: brown\nExample: Il tavolo Ã¨ **marrone**",
]

[[notes]]
note_id = 10008
tags = [
    "a1",
    "colori",
]
fields = [
    "âš« **nero**",
    "Meaning: black\nExample: La scarpa Ã¨ **nera**",
]

[[notes]]
note_id = 10009
tags = [
    "a1",
    "colori",
]
fields = [
    "âšª **bianco**",
    "Meaning: white\nExample: Il muro Ã¨ **bianco**",
]

[[notes]]
note_id = 10010
tags = [
    "a1",
    "colori",
]
fields = [
    "ğŸ”˜ **grigio**",
    "Meaning: gray\nExample: Il gatto Ã¨ **grigio**",
]

[[notes]]
note_id = 10011
tags = [
    "a1",
    "colori",
]
fields = [
    "ğŸŒ¸ **rosa**",
    "Meaning: pink\nExample: La maglia Ã¨ **rosa**",
]

[[notes]]
note_id = 10012
tags = [
    "a1",
    "colori",
]
fields = [
    "â˜€ï¸ **giallo chiaro**",
    "Meaning: light yellow\nExample: Il vestito Ã¨ **giallo chiaro**",
]

[[notes]]
note_id = 10013
tags = [
    "a1",
    "colori",
]
fields = [
    "ğŸŒŠ **azzurro**",
    "Meaning: light blue\nExample: La piscina Ã¨ **azzurra**",
]

[[notes]]
note_id = 10014
tags = [
    "a1",
    "colori",
]
fields = [
    "ğŸ¦„ **turchese**",
    "Meaning: turquoise\nExample: Le onde sono **turchesi**",
]

[[notes]]
note_id = 10015
tags = [
    "a1",
    "colori",
]
fields = [
    "âœ¨ **oro**",
    "Meaning: gold\nExample: Lâ€™anello Ã¨ **dâ€™oro**",
]

[[notes]]
note_id = 10016
tags = [
    "a1",
    "colori",
]
fields = [
    "ğŸŒŸ **argento**",
    "Meaning: silver\nExample: Il bracciale Ã¨ **argento**",
]

[[notes]]
note_id = 10017
tags = [
    "a1",
    "colori",
]
fields = [
    "ğŸ¤ **beige**",
    "Meaning: beige\nExample: Il divano Ã¨ **beige**",
]

[[notes]]
note_id = 10018
tags = [
    "a1",
    "colori",
]
fields = [
    "ğŸ€ **lilla**",
    "Meaning: lilac\nExample: La sciarpa Ã¨ **lilla**",
]

[[notes]]
note_id = 10019
tags = [
    "a1",
    "colori",
]
fields = [
    "ğŸ’– **fucsia**",
    "Meaning: fuchsia\nExample: La borsa Ã¨ **fucsia**",
]

[[notes]]
note_id = 10020
tags = [
    "a1",
    "colori",
]
fields = [
    "ğŸƒ **verde scuro**",
    "Meaning: dark green\nExample: La foresta Ã¨ **verde scuro**",
]
