deck = "a1::dimostrativi"
model = "basic"

[[notes]]
note_id = 10001
tags = [
    "a1",
    "dimostrativi",
]
fields = [
    "ğŸ“˜ **questo libro**",
    "Meaning: this book\nExample: Prendo **questo libro**",
]

[[notes]]
note_id = 10002
tags = [
    "a1",
    "dimostrativi",
]
fields = [
    "ğŸ‘— **questa gonna**",
    "Meaning: this skirt\nExample: Provo **questa gonna**",
]

[[notes]]
note_id = 10003
tags = [
    "a1",
    "dimostrativi",
]
fields = [
    "ğŸ“š **questi libri**",
    "Meaning: these books\nExample: Leggo **questi libri**",
]

[[notes]]
note_id = 10004
tags = [
    "a1",
    "dimostrativi",
]
fields = [
    "ğŸ‘  **queste scarpe**",
    "Meaning: these shoes\nExample: Indosso **queste scarpe**",
]

[[notes]]
note_id = 10005
tags = [
    "a1",
    "dimostrativi",
]
fields = [
    "ğŸ“• **quel libro**",
    "Meaning: that book\nExample: Vedo **quel libro**",
]

[[notes]]
note_id = 10006
tags = [
    "a1",
    "dimostrativi",
]
fields = [
    "ğŸ  **quella casa**",
    "Meaning: that house\nExample: Visito **quella casa**",
]

[[notes]]
note_id = 10007
tags = [
    "a1",
    "dimostrativi",
]
fields = [
    "ğŸ‘ **quei pantaloni**",
    "Meaning: those trousers\nExample: Lavo **quei pantaloni**",
]

[[notes]]
note_id = 10008
tags = [
    "a1",
    "dimostrativi",
]
fields = [
    "ğŸŒ· **quelle rose**",
    "Meaning: those roses\nExample: Colgo **quelle rose**",
]

[[notes]]
note_id = 10009
tags = [
    "a1",
    "dimostrativi",
]
fields = [
    "ğŸ‘¨â€ğŸ¦³ **quest'uomo**",
    "Meaning: this man\nExample: Parlo con **quest'uomo**",
]

[[notes]]
note_id = 10010
tags = [
    "a1",
    "dimostrativi",
]
fields = [
    "ğŸ‘©â€ğŸ¦° **quest'amica**",
    "Meaning: this friend (f.)\nExample: Vedo **quest'amica**",
]

[[notes]]
note_id = 10011
tags = [
    "a1",
    "dimostrativi",
]
fields = [
    "ğŸ‘¨ **quell'uomo**",
    "Meaning: that man\nExample: Conosco **quell'uomo**",
]

[[notes]]
note_id = 10012
tags = [
    "a1",
    "dimostrativi",
]
fields = [
    "ğŸ‘© **quell'amica**",
    "Meaning: that friend (f.)\nExample: Invito **quell'amica**",
]

[[notes]]
note_id = 10013
tags = [
    "a1",
    "dimostrativi",
]
fields = [
    "ğŸŒ **questo giorno**",
    "Meaning: this day\nExample: Amo **questo giorno**",
]

[[notes]]
note_id = 10014
tags = [
    "a1",
    "dimostrativi",
]
fields = [
    "ğŸŒ› **quella sera**",
    "Meaning: that evening\nExample: Ricordo **quella sera**",
]

[[notes]]
note_id = 10015
tags = [
    "a1",
    "dimostrativi",
]
fields = [
    "ğŸ—“ **questi giorni**",
    "Meaning: these days\nExample: Studio **questi giorni**",
]

[[notes]]
note_id = 10016
tags = [
    "a1",
    "dimostrativi",
]
fields = [
    "ğŸŒ™ **quelle sere**",
    "Meaning: those evenings\nExample: Esco **quelle sere**",
]

[[notes]]
note_id = 10017
tags = [
    "a1",
    "dimostrativi",
]
fields = [
    "â° **quest'ora**",
    "Meaning: this hour\nExample: Aspetta **quest'ora**",
]

[[notes]]
note_id = 10018
tags = [
    "a1",
    "dimostrativi",
]
fields = [
    "ğŸ•° **quell'ora**",
    "Meaning: that hour\nExample: Arrivo a **quell'ora**",
]

[[notes]]
note_id = 10019
tags = [
    "a1",
    "dimostrativi",
]
fields = [
    "ğŸ‘« **questi amici**",
    "Meaning: these friends\nExample: Invito **questi amici**",
]

[[notes]]
note_id = 10020
tags = [
    "a1",
    "dimostrativi",
]
fields = [
    "ğŸ‘¥ **quelle persone**",
    "Meaning: those people\nExample: Incontro **quelle persone**",
]
