deck = "a1::mesi_e_stagioni"
model = "basic"

[[notes]]
note_id = 10001
tags = [
    "a1",
    "mesi_e_stagioni",
]
fields = [
    "ğŸ—“ **gennaio**",
    "Meaning: January\nExample: Gennaio Ã¨ freddo",
]

[[notes]]
note_id = 10002
tags = [
    "a1",
    "mesi_e_stagioni",
]
fields = [
    "ğŸ—“ **febbraio**",
    "Meaning: February\nExample: Febbraio ha 28 giorni",
]

[[notes]]
note_id = 10003
tags = [
    "a1",
    "mesi_e_stagioni",
]
fields = [
    "ğŸ—“ **marzo**",
    "Meaning: March\nExample: Marzo Ã¨ primavera",
]

[[notes]]
note_id = 10004
tags = [
    "a1",
    "mesi_e_stagioni",
]
fields = [
    "ğŸ—“ **aprile**",
    "Meaning: April\nExample: Ad aprile piove spesso",
]

[[notes]]
note_id = 10005
tags = [
    "a1",
    "mesi_e_stagioni",
]
fields = [
    "ğŸ—“ **maggio**",
    "Meaning: May\nExample: Maggio Ã¨ mese dei fiori",
]

[[notes]]
note_id = 10006
tags = [
    "a1",
    "mesi_e_stagioni",
]
fields = [
    "ğŸ—“ **giugno**",
    "Meaning: June\nExample: Giugno Ã¨ estate",
]

[[notes]]
note_id = 10007
tags = [
    "a1",
    "mesi_e_stagioni",
]
fields = [
    "ğŸ—“ **luglio**",
    "Meaning: July\nExample: A luglio fa molto caldo",
]

[[notes]]
note_id = 10008
tags = [
    "a1",
    "mesi_e_stagioni",
]
fields = [
    "ğŸ—“ **agosto**",
    "Meaning: August\nExample: Agosto Ã¨ mese di ferie",
]

[[notes]]
note_id = 10009
tags = [
    "a1",
    "mesi_e_stagioni",
]
fields = [
    "ğŸ—“ **settembre**",
    "Meaning: September\nExample: A settembre inizia la scuola",
]

[[notes]]
note_id = 10010
tags = [
    "a1",
    "mesi_e_stagioni",
]
fields = [
    "ğŸ—“ **ottobre**",
    "Meaning: October\nExample: Ottobre Ã¨ autunnale",
]

[[notes]]
note_id = 10011
tags = [
    "a1",
    "mesi_e_stagioni",
]
fields = [
    "ğŸ—“ **novembre**",
    "Meaning: November\nExample: Novembre Ã¨ piovoso",
]

[[notes]]
note_id = 10012
tags = [
    "a1",
    "mesi_e_stagioni",
]
fields = [
    "ğŸ—“ **dicembre**",
    "Meaning: December\nExample: Dicembre ha il Natale",
]

[[notes]]
note_id = 10013
tags = [
    "a1",
    "mesi_e_stagioni",
]
fields = [
    "â„ï¸ **inverno**",
    "Meaning: winter\nExample: Lâ€™inverno Ã¨ freddo",
]

[[notes]]
note_id = 10014
tags = [
    "a1",
    "mesi_e_stagioni",
]
fields = [
    "ğŸŒ¸ **primavera**",
    "Meaning: spring\nExample: La primavera Ã¨ fiorita",
]

[[notes]]
note_id = 10015
tags = [
    "a1",
    "mesi_e_stagioni",
]
fields = [
    "ğŸŒ **estate**",
    "Meaning: summer\nExample: Lâ€™estate Ã¨ calda",
]

[[notes]]
note_id = 10016
tags = [
    "a1",
    "mesi_e_stagioni",
]
fields = [
    "ğŸ‚ **autunno**",
    "Meaning: autumn\nExample: Lâ€™autunno Ã¨ ventoso",
]

[[notes]]
note_id = 10017
tags = [
    "a1",
    "mesi_e_stagioni",
]
fields = [
    "ğŸ“† **ogni mese**",
    "Meaning: every month\nExample: Visito nonno **ogni mese**",
]

[[notes]]
note_id = 10018
tags = [
    "a1",
    "mesi_e_stagioni",
]
fields = [
    "ğŸ“… **questo mese**",
    "Meaning: this month\nExample: **Questo mese** imparo lâ€™italiano",
]

[[notes]]
note_id = 10019
tags = [
    "a1",
    "mesi_e_stagioni",
]
fields = [
    "ğŸ“‰ **mese scorso**",
    "Meaning: last month\nExample: **Mese scorso** ho viaggiato",
]

[[notes]]
note_id = 10020
tags = [
    "a1",
    "mesi_e_stagioni",
]
fields = [
    "ğŸ“ˆ **mese prossimo**",
    "Meaning: next month\nExample: **Mese prossimo** farÃ² una festa",
]
