deck = "a1::orario"
model = "basic"

[[notes]]
note_id = 10001
tags = [
    "a1",
    "orario",
]
fields = [
    "ğŸ• **lâ€™una**",
    "Meaning: one oâ€™clock",
]

[[notes]]
note_id = 10002
tags = [
    "a1",
    "orario",
]
fields = [
    "ğŸ•‘ **le due**",
    "Meaning: two oâ€™clock",
]

[[notes]]
note_id = 10003
tags = [
    "a1",
    "orario",
]
fields = [
    "ğŸ•’ **le tre**",
    "Meaning: three oâ€™clock",
]

[[notes]]
note_id = 10004
tags = [
    "a1",
    "orario",
]
fields = [
    "ğŸ•“ **le quattro**",
    "Meaning: four oâ€™clock",
]

[[notes]]
note_id = 10005
tags = [
    "a1",
    "orario",
]
fields = [
    "ğŸ•” **le cinque**",
    "Meaning: five oâ€™clock",
]

[[notes]]
note_id = 10006
tags = [
    "a1",
    "orario",
]
fields = [
    "ğŸ•• **le sei**",
    "Meaning: six oâ€™clock",
]

[[notes]]
note_id = 10007
tags = [
    "a1",
    "orario",
]
fields = [
    "ğŸ•– **le sette**",
    "Meaning: seven oâ€™clock",
]

[[notes]]
note_id = 10008
tags = [
    "a1",
    "orario",
]
fields = [
    "ğŸ•— **le otto**",
    "Meaning: eight oâ€™clock",
]

[[notes]]
note_id = 10009
tags = [
    "a1",
    "orario",
]
fields = [
    "ğŸ•˜ **le nove**",
    "Meaning: nine oâ€™clock",
]

[[notes]]
note_id = 10010
tags = [
    "a1",
    "orario",
]
fields = [
    "ğŸ•™ **le dieci**",
    "Meaning: ten oâ€™clock",
]

[[notes]]
note_id = 10011
tags = [
    "a1",
    "orario",
]
fields = [
    "ğŸ•š **le undici**",
    "Meaning: eleven oâ€™clock",
]

[[notes]]
note_id = 10012
tags = [
    "a1",
    "orario",
]
fields = [
    "ğŸ•› **le dodici**",
    "Meaning: twelve oâ€™clock",
]

[[notes]]
note_id = 10013
tags = [
    "a1",
    "orario",
]
fields = [
    "ğŸŒ… **mattina**",
    "Meaning: morning",
]

[[notes]]
note_id = 10014
tags = [
    "a1",
    "orario",
]
fields = [
    "ğŸŒ‡ **sera**",
    "Meaning: evening",
]

[[notes]]
note_id = 10015
tags = [
    "a1",
    "orario",
]
fields = [
    "â˜€ï¸ **giorno**",
    "Meaning: daytime",
]

[[notes]]
note_id = 10016
tags = [
    "a1",
    "orario",
]
fields = [
    "ğŸŒ™ **notte**",
    "Meaning: night",
]

[[notes]]
note_id = 10017
tags = [
    "a1",
    "orario",
]
fields = [
    "ğŸ”œ **presto**",
    "Meaning: early/soon",
]

[[notes]]
note_id = 10018
tags = [
    "a1",
    "orario",
]
fields = [
    "ğŸ”š **tardi**",
    "Meaning: late",
]

[[notes]]
note_id = 10019
tags = [
    "a1",
    "orario",
]
fields = [
    "â° **mezzogiorno**",
    "Meaning: noon",
]

[[notes]]
note_id = 10020
tags = [
    "a1",
    "orario",
]
fields = [
    "ğŸŒƒ **mezzanotte**",
    "Meaning: midnight",
]
