deck = "a1::sostantivi"
model = "basic"

[[notes]]
note_id = 10001
tags = [
    "a1",
    "sostantivi",
]
fields = [
    "ğŸ  **casa**",
    "Meaning: house\nExample: La mia **casa** Ã¨ grande",
]

[[notes]]
note_id = 10002
tags = [
    "a1",
    "sostantivi",
]
fields = [
    "ğŸš— **macchina**",
    "Meaning: car\nExample: La **macchina** Ã¨ nuova",
]

[[notes]]
note_id = 10003
tags = [
    "a1",
    "sostantivi",
]
fields = [
    "ğŸ« **scuola**",
    "Meaning: school\nExample: Vado a **scuola** ogni giorno",
]

[[notes]]
note_id = 10004
tags = [
    "a1",
    "sostantivi",
]
fields = [
    "ğŸ‘« **amico**",
    "Meaning: friend\nExample: Ho un **amico** italiano",
]

[[notes]]
note_id = 10005
tags = [
    "a1",
    "sostantivi",
]
fields = [
    "ğŸ‘ª **famiglia**",
    "Meaning: family\nExample: La mia **famiglia** Ã¨ numerosa",
]

[[notes]]
note_id = 10006
tags = [
    "a1",
    "sostantivi",
]
fields = [
    "ğŸ½ **tavolo**",
    "Meaning: table\nExample: Il **tavolo** Ã¨ di legno",
]

[[notes]]
note_id = 10007
tags = [
    "a1",
    "sostantivi",
]
fields = [
    "ğŸª‘ **sedia**",
    "Meaning: chair\nExample: La **sedia** Ã¨ comoda",
]

[[notes]]
note_id = 10008
tags = [
    "a1",
    "sostantivi",
]
fields = [
    "ğŸ“– **libro**",
    "Meaning: book\nExample: Leggo un **libro**",
]

[[notes]]
note_id = 10009
tags = [
    "a1",
    "sostantivi",
]
fields = [
    "ğŸ–Š **penna**",
    "Meaning: pen\nExample: Scrivo con una **penna**",
]

[[notes]]
note_id = 10010
tags = [
    "a1",
    "sostantivi",
]
fields = [
    "ğŸ›£ **strada**",
    "Meaning: road\nExample: La **strada** Ã¨ larga",
]

[[notes]]
note_id = 10011
tags = [
    "a1",
    "sostantivi",
]
fields = [
    "ğŸ **cibo**",
    "Meaning: food\nExample: Il **cibo** Ã¨ delizioso",
]

[[notes]]
note_id = 10012
tags = [
    "a1",
    "sostantivi",
]
fields = [
    "ğŸ’§ **acqua**",
    "Meaning: water\nExample: Bevo **acqua** fredda",
]

[[notes]]
note_id = 10013
tags = [
    "a1",
    "sostantivi",
]
fields = [
    "ğŸšª **porta**",
    "Meaning: door\nExample: Apri la **porta**",
]

[[notes]]
note_id = 10014
tags = [
    "a1",
    "sostantivi",
]
fields = [
    "ğŸªŸ **finestra**",
    "Meaning: window\nExample: La **finestra** Ã¨ aperta",
]

[[notes]]
note_id = 10015
tags = [
    "a1",
    "sostantivi",
]
fields = [
    "ğŸŒŒ **spazio**",
    "Meaning: space\nExample: Câ€™Ã¨ molto **spazio** qui",
]

[[notes]]
note_id = 10016
tags = [
    "a1",
    "sostantivi",
]
fields = [
    "â³ **tempo**",
    "Meaning: time\nExample: Non ho abbastanza **tempo**",
]

[[notes]]
note_id = 10017
tags = [
    "a1",
    "sostantivi",
]
fields = [
    "ğŸ’¼ **lavoro**",
    "Meaning: work\nExample: Il **lavoro** Ã¨ impegnativo",
]

[[notes]]
note_id = 10018
tags = [
    "a1",
    "sostantivi",
]
fields = [
    "ğŸ’¶ **soldi**",
    "Meaning: money\nExample: Non ho molti **soldi**",
]

[[notes]]
note_id = 10019
tags = [
    "a1",
    "sostantivi",
]
fields = [
    "ğŸ™ **cittÃ **",
    "Meaning: city\nExample: Amo la mia **cittÃ **",
]

[[notes]]
note_id = 10020
tags = [
    "a1",
    "sostantivi",
]
fields = [
    "ğŸŒ„ **paese**",
    "Meaning: village/country\nExample: Vivo in un piccolo **paese**",
]
